name: proxmox-make
description: Create multi-arch Proxmox packages
inputs:
  project-dir:
    required: false
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: ProtonDI/proxmox-make-action
        path: .ci
    - name: Build
      shell: bash
      run: |
        .ci/proxmox-make ${{ inputs.project-dir }}
